name: 'Spellcheck'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: spelling or typos
        uses: actions/checkout@v3
      - name: fix permission for reviewdog
        run: sudo chown -R root:root $GITHUB_WORKSPACE
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
          fail_on_error: true
